In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('VPA_Open_Space.csv')

In [3]:
data.head()

,FID,LGA,VM_PARCEL_,VM_PARCE_1,DATA_SOURC,OS_CATEGOR,OS_CATEG_2,OWNER_TYPE,PARK_NAME,OS_STATUS,...,VEAC_ID,WATER_BODY,OS_TYPE,COASTAL,MANAGER_NA,OWNER_NAME,Image_URL,VPA_ID,SHAPE_Length,SHAPE_Area
0,1,BOROONDARA,3\LP28215,95086,VM Features of Interest,Tertiary institutions,Not applicable,State Government,Swinburne University Of Technology & Tafe Divi...,Existing,...,,,Restricted public land,,NO DATA,Swinburne University of Technology,https://lh3.googleusercontent.com/-QP2NylEZuhE...,1500,0.000742,1.700000e-08
1,2,BOROONDARA,159\LP5481,203973157,VM Parcels,Parks and gardens,Not applicable,Local government,Kate Campbell Reserve,Existing,...,,,Public open space,,NO DATA,Boroondara City Council,https://lh3.googleusercontent.com/-rdTUgqfNyXg...,1501,0.001105,6.530000e-08
2,3,BOROONDARA,3\TP84208,203973089,VM Parcels,Parks and gardens,Not applicable,Local government,Kate Campbell Reserve,Existing,...,,,Public open space,,NO DATA,Boroondara City Council,https://lh3.googleusercontent.com/-rdTUgqfNyXg...,1502,0.001003,5.620000e-08
3,4,BOROONDARA,1\TP84208,203973073,VM Parcels,Parks and gardens,Not applicable,Local government,Kate Campbell Reserve,Existing,...,,,Public open space,,NO DATA,Boroondara City Council,https://lh3.googleusercontent.com/-rdTUgqfNyXg...,1503,0.001102,6.530000e-08
4,5,BOROONDARA,1\TP802753,203972979,VM Parcels,Parks and gardens,Not applicable,Local government,Kate Campbell Reserve,Existing,...,,,Public open space,,NO DATA,Boroondara City Council,https://lh3.googleusercontent.com/-rdTUgqfNyXg...,1504,0.001327,9.440000e-08

In [4]:
data.columns

Index(['FID', 'LGA', 'VM_PARCEL_', 'VM_PARCE_1', 'DATA_SOURC', 'OS_CATEGOR',
       'OS_CATEG_2', 'OWNER_TYPE', 'PARK_NAME', 'OS_STATUS', 'OS_ACCESS',
       'MANAGER_TY', 'HA', 'SUBREGION', 'VEAC_ID', 'WATER_BODY', 'OS_TYPE',
       'COASTAL', 'MANAGER_NA', 'OWNER_NAME', 'Image_URL', 'VPA_ID',
       'SHAPE_Length', 'SHAPE_Area'],
      dtype='object')

In [5]:
data['OS_CATEGOR'].unique()

array(['Tertiary institutions', 'Parks and gardens',
       'Transport reservations', 'Sportsfields and organised recreation',
       'Recreation corridor', 'Government schools',
       'Natural and semi-natural open space',
       'Services and utilities reserves', 'Non-government schools',
       'Conservation reserves', 'Cemeteries',
       'Civic squares and promenades', 'Public housing reserves'],
      dtype=object)

In [6]:
selected = ['LGA', 'PARK_NAME', 'OS_CATEGOR', 'OS_ACCESS', 'VM_PARCE_1']
selected_df = data[selected]

In [7]:
selected_df

,LGA,PARK_NAME,OS_CATEGOR,OS_ACCESS
0,BOROONDARA,Swinburne University Of Technology & Tafe Divi...,Tertiary institutions,Limited
1,BOROONDARA,Kate Campbell Reserve,Parks and gardens,Open
2,BOROONDARA,Kate Campbell Reserve,Parks and gardens,Open
3,BOROONDARA,Kate Campbell Reserve,Parks and gardens,Open
4,BOROONDARA,Kate Campbell Reserve,Parks and gardens,Open
...,...,...,...,...
38805,FRANKSTON,Taverner Square Reserve,Transport reservations,Open
38806,YARRA,St Kevins College - Waterford,Non-government schools,Closed
38807,FRANKSTON,Seaford Swamp (MWC Drain),Natural and semi-natural open space,Open
38808,FRANKSTON,Broughton Reserve,Parks and gardens,Open
38809,FRANKSTON,McCormicks Road Reserve Link,Transport reservations,Open

In [8]:
limited_category = selected_df[(selected_df['OS_CATEGOR'] != 'Transport reservations') &
                              (selected_df['OS_CATEGOR'] != 'Services and utilities reserves') &
                              (selected_df['OS_CATEGOR'] != 'Non-government schools') &
                              (selected_df['OS_CATEGOR'] != 'Government schools') &
                              (selected_df['OS_CATEGOR'] != 'Civic squares and promenades') &
                              (selected_df['VM_PARCE_1'] != 'NO DATA')] # These rows don't have valid Park name

In [9]:
limited_category

,LGA,PARK_NAME,OS_CATEGOR,OS_ACCESS
0,BOROONDARA,Swinburne University Of Technology & Tafe Divi...,Tertiary institutions,Limited
1,BOROONDARA,Kate Campbell Reserve,Parks and gardens,Open
2,BOROONDARA,Kate Campbell Reserve,Parks and gardens,Open
3,BOROONDARA,Kate Campbell Reserve,Parks and gardens,Open
4,BOROONDARA,Kate Campbell Reserve,Parks and gardens,Open
...,...,...,...,...
38802,FRANKSTON,Jubilee Park,Sportsfields and organised recreation,Open
38803,FRANKSTON,Seaford Swamp (MWC Drain),Natural and semi-natural open space,Open
38804,FRANKSTON,Seaford Swamp (MWC Drain),Natural and semi-natural open space,Open
38807,FRANKSTON,Seaford Swamp (MWC Drain),Natural and semi-natural open space,Open
38808,FRANKSTON,Broughton Reserve,Parks and gardens,Open

In [10]:
limited_category['OS_CATEGOR'].mask(limited_category['OS_CATEGOR'] == 'Recreation corridor', 'Recreational Reserve', inplace = True)

limited_category['OS_CATEGOR'].mask(limited_category['OS_CATEGOR'] == 'Natural and semi-natural open space', 'Natural attraction (reserves)', inplace = True)

limited_category['OS_CATEGOR'].mask(limited_category['OS_CATEGOR'] == 'Conservation reserves', 'Natural attraction (reserves)', inplace = True)

D:\anaconda3\lib\site-packages\pandas\core\generic.py:8765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)

In [11]:
limited_category

,LGA,PARK_NAME,OS_CATEGOR,OS_ACCESS
0,BOROONDARA,Swinburne University Of Technology & Tafe Divi...,Tertiary institutions,Limited
1,BOROONDARA,Kate Campbell Reserve,Parks and gardens,Open
2,BOROONDARA,Kate Campbell Reserve,Parks and gardens,Open
3,BOROONDARA,Kate Campbell Reserve,Parks and gardens,Open
4,BOROONDARA,Kate Campbell Reserve,Parks and gardens,Open
...,...,...,...,...
38802,FRANKSTON,Jubilee Park,Sportsfields and organised recreation,Open
38803,FRANKSTON,Seaford Swamp (MWC Drain),Natural attraction (reserves),Open
38804,FRANKSTON,Seaford Swamp (MWC Drain),Natural attraction (reserves),Open
38807,FRANKSTON,Seaford Swamp (MWC Drain),Natural attraction (reserves),Open
38808,FRANKSTON,Broughton Reserve,Parks and gardens,Open

In [12]:
limited_category['OS_CATEGOR'].unique()

array(['Tertiary institutions', 'Parks and gardens',
       'Sportsfields and organised recreation', 'Recreational Reserve',
       'Natural attraction (reserves)', 'Cemeteries',
       'Public housing reserves'], dtype=object)

In [13]:
open_park = limited_category[limited_category['OS_ACCESS'] == 'Open']

In [14]:
open_park

,LGA,PARK_NAME,OS_CATEGOR,OS_ACCESS
1,BOROONDARA,Kate Campbell Reserve,Parks and gardens,Open
2,BOROONDARA,Kate Campbell Reserve,Parks and gardens,Open
3,BOROONDARA,Kate Campbell Reserve,Parks and gardens,Open
4,BOROONDARA,Kate Campbell Reserve,Parks and gardens,Open
6,BOROONDARA,Jack Otoole Reserve,Sportsfields and organised recreation,Open
...,...,...,...,...
38802,FRANKSTON,Jubilee Park,Sportsfields and organised recreation,Open
38803,FRANKSTON,Seaford Swamp (MWC Drain),Natural attraction (reserves),Open
38804,FRANKSTON,Seaford Swamp (MWC Drain),Natural attraction (reserves),Open
38807,FRANKSTON,Seaford Swamp (MWC Drain),Natural attraction (reserves),Open
38808,FRANKSTON,Broughton Reserve,Parks and gardens,Open

In [15]:
open_park['OS_CATEGOR'].unique()

array(['Parks and gardens', 'Sportsfields and organised recreation',
       'Recreational Reserve', 'Natural attraction (reserves)'],
      dtype=object)

In [16]:
remove_duplicated_park = open_park.drop_duplicates(keep='first')

In [17]:
remove_duplicated_park

,LGA,PARK_NAME,OS_CATEGOR,OS_ACCESS
1,BOROONDARA,Kate Campbell Reserve,Parks and gardens,Open
6,BOROONDARA,Jack Otoole Reserve,Sportsfields and organised recreation,Open
12,BOROONDARA,Hays Paddock,Parks and gardens,Open
15,WYNDHAM,Bay Trail,Recreational Reserve,Open
22,BOROONDARA,,Recreational Reserve,Open
...,...,...,...,...
38740,FRANKSTON,Sweetwater Creek Nature Reserve,Natural attraction (reserves),Open
38744,FRANKSTON,Wallace Link,Recreational Reserve,Open
38750,FRANKSTON,Montague Park,Recreational Reserve,Open
38791,FRANKSTON,"Retarding Basins, O'Gradys Road",Natural attraction (reserves),Open
38808,FRANKSTON,Broughton Reserve,Parks and gardens,Open

In [18]:
# drop empty string or white space row
remove_empty_park = remove_duplicated_park[remove_duplicated_park['PARK_NAME'].str.strip().astype(bool)]

In [19]:
remove_empty_park

,LGA,PARK_NAME,OS_CATEGOR,OS_ACCESS
1,BOROONDARA,Kate Campbell Reserve,Parks and gardens,Open
6,BOROONDARA,Jack Otoole Reserve,Sportsfields and organised recreation,Open
12,BOROONDARA,Hays Paddock,Parks and gardens,Open
15,WYNDHAM,Bay Trail,Recreational Reserve,Open
48,BOROONDARA,Boroondara Park,Parks and gardens,Open
...,...,...,...,...
38740,FRANKSTON,Sweetwater Creek Nature Reserve,Natural attraction (reserves),Open
38744,FRANKSTON,Wallace Link,Recreational Reserve,Open
38750,FRANKSTON,Montague Park,Recreational Reserve,Open
38791,FRANKSTON,"Retarding Basins, O'Gradys Road",Natural attraction (reserves),Open
38808,FRANKSTON,Broughton Reserve,Parks and gardens,Open

In [20]:
swimming_pool = pd.read_csv('swimming pool final.csv')

In [21]:
selected_park = ['LGA', 'PARK_NAME', 'OS_CATEGOR']
park_df = remove_empty_park[selected_park]

In [22]:
park_df.rename(columns={'OS_CATEGOR':'CATEGORY'}, inplace=True)

D:\anaconda3\lib\site-packages\pandas\core\frame.py:4125: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [23]:
park_df

,LGA,PARK_NAME,CATEGORY
1,BOROONDARA,Kate Campbell Reserve,Parks and gardens
6,BOROONDARA,Jack Otoole Reserve,Sportsfields and organised recreation
12,BOROONDARA,Hays Paddock,Parks and gardens
15,WYNDHAM,Bay Trail,Recreational Reserve
48,BOROONDARA,Boroondara Park,Parks and gardens
...,...,...,...
38740,FRANKSTON,Sweetwater Creek Nature Reserve,Natural attraction (reserves)
38744,FRANKSTON,Wallace Link,Recreational Reserve
38750,FRANKSTON,Montague Park,Recreational Reserve
38791,FRANKSTON,"Retarding Basins, O'Gradys Road",Natural attraction (reserves)
38808,FRANKSTON,Broughton Reserve,Parks and gardens

In [24]:
park_swim_df = pd.concat([park_df,swimming_pool])

In [25]:
track_df = pd.read_csv('tmpcSTzXmtracking.csv', header=None)

In [26]:
track_df

,0,1,2,3,4,5,6,7
0,Australian Alps Walking Track,NaN,Alpine National Park,3825,VIC,Tracks/Trails,NaN,NaN
1,Ballarat-Skipton Railtrail,NaN,Ballarat,3350,VIC,Tracks/Trails,Ballarat,Grampians
2,Barmah Lakes Loop Track,NaN,Barmah State Park and Forest,3639,VIC,Tracks/Trails,NaN,NaN
3,Bayside Trail - Williamstown-Brighton,NaN,Melbourne,3000,VIC,Tracks/Trails,Melbourne,North and West Metropolitan Region
4,Beehive Falls Trail,Grampians National Park,Grampians,3381,VIC,Tracks/Trails,NaN,NaN
...,...,...,...,...,...,...,...,...
110,Wilsons Prom Circuit Trail,NaN,Wilsons Promontory National Park,3960,VIC,Tracks/Trails,NaN,NaN
111,Wirrawilla Walk - Toolangi State Forest,NaN,Toolangi State Forest,3777,VIC,Tracks/Trails,NaN,NaN
112,Wonderland Loop Walk,NaN,Grampians National Park,3381,VIC,Tracks/Trails,NaN,NaN
113,Woolshed Falls Historic Walk,NaN,Beechworth Historic Park,3747,VIC,Tracks/Trails,NaN,NaN
114,Wreck Beach Trail,NaN,Otway National Park,3238,VIC,Tracks/Trails,NaN,NaN

In [27]:
track_selected = track_df.drop(columns=[1,2,4,6,7])

In [28]:
track_selected

                                           0     3              5
0              Australian Alps Walking Track  3825  Tracks/Trails
1                 Ballarat-Skipton Railtrail  3350  Tracks/Trails
2                    Barmah Lakes Loop Track  3639  Tracks/Trails
3      Bayside Trail - Williamstown-Brighton  3000  Tracks/Trails
4                        Beehive Falls Trail  3381  Tracks/Trails
..                                       ...   ...            ...
110               Wilsons Prom Circuit Trail  3960  Tracks/Trails
111  Wirrawilla Walk - Toolangi State Forest  3777  Tracks/Trails
112                     Wonderland Loop Walk  3381  Tracks/Trails
113             Woolshed Falls Historic Walk  3747  Tracks/Trails
114                        Wreck Beach Trail  3238  Tracks/Trails

[115 rows x 3 columns]

In [29]:
track_selected.rename(columns={0:'PARK_NAME', 3:'POST_CODE', 5:'CATEGORY'}, inplace=True)

In [30]:
track_selected

                                   PARK_NAME  POST_CODE       CATEGORY
0              Australian Alps Walking Track       3825  Tracks/Trails
1                 Ballarat-Skipton Railtrail       3350  Tracks/Trails
2                    Barmah Lakes Loop Track       3639  Tracks/Trails
3      Bayside Trail - Williamstown-Brighton       3000  Tracks/Trails
4                        Beehive Falls Trail       3381  Tracks/Trails
..                                       ...        ...            ...
110               Wilsons Prom Circuit Trail       3960  Tracks/Trails
111  Wirrawilla Walk - Toolangi State Forest       3777  Tracks/Trails
112                     Wonderland Loop Walk       3381  Tracks/Trails
113             Woolshed Falls Historic Walk       3747  Tracks/Trails
114                        Wreck Beach Trail       3238  Tracks/Trails

[115 rows x 3 columns]

In [31]:
locality = pd.read_csv('locality.csv')

In [32]:
locality

      LOCALITY_ID      SUBURB                 LGA  POST_CODE
0         1000001    Abbeyard              ALPINE       3737
1         1000002  Abbotsford               YARRA       3067
2         1000003  Aberfeldie       MOONEE VALLEY       3040
3         1000004   Aberfeldy             BAW BAW       3825
4         1000005     Acheron         MURRINDINDI       3714
...           ...         ...                 ...        ...
3216      1003217    Yulecart  SOUTHERN GRAMPIANS       3301
3217      1003218     Yundool               MOIRA       3727
3218      1003219      Yuroke                HUME       3063
3219      1003220     Yuulong         COLAC OTWAY       3237
3220      1003221     Zeerust  GREATER SHEPPARTON       3634

[3221 rows x 4 columns]

In [33]:
track_post_code = track_selected['POST_CODE'].unique().tolist()

In [34]:
track_lga = []
for code in track_post_code:
    for idx,row in locality.iterrows():
        if row['POST_CODE'] == code:
            temp = []
            temp.append(code)
            temp.append(row['LGA'])
            if temp not in track_lga:
                track_lga.append(temp)

In [35]:
track_lga

[[3825, 'BAW BAW'],
 [3825, 'LATROBE'],
 [3350, 'BALLARAT'],
 [3639, 'MOIRA'],
 [3000, 'MELBOURNE'],
 [3381, 'NORTHERN GRAMPIANS'],
 [3381, 'ARARAT RURAL'],
 [3373, 'PYRENEES'],
 [3373, 'ARARAT RURAL'],
 [3213, 'GOLDEN PLAINS'],
 [3213, 'GREATER GEELONG'],
 [3550, 'GREATER BENDIGO'],
 [3305, 'GLENELG'],
 [3777, 'YARRA RANGES'],
 [3777, 'MURRINDINDI'],
 [3700, 'TOWONG'],
 [3858, 'WELLINGTON'],
 [3500, 'MILDURA RURAL'],
 [3936, 'MORNINGTON'],
 [3888, 'EAST GIPPSLAND'],
 [3233, 'COLAC OTWAY'],
 [3922, 'BASS COAST'],
 [3006, 'MELBOURNE'],
 [3006, 'PORT PHILLIP'],
 [3280, 'MOYNE'],
 [3280, 'WARRNAMBOOL'],
 [3300, 'SOUTHERN GRAMPIANS'],
 [3779, 'MURRINDINDI'],
 [3875, 'EAST GIPPSLAND'],
 [3414, 'HINDMARSH'],
 [3414, 'YARRIAMBIACK'],
 [3450, 'MOUNT ALEXANDER'],
 [3971, 'WELLINGTON'],
 [3971, 'LATROBE'],
 [3440, 'MACEDON RANGES'],
 [3891, 'EAST GIPPSLAND'],
 [3741, 'ALPINE'],
 [3741, 'UNINCORPORATED'],
 [3747, 'INDIGO'],
 [3747, 'WANGARATTA RURAL'],
 [3953, 'SOUTH GIPPSLAND'],
 [3953, 'BAW BAW'],
 [3442, 'MACEDON RANGES'],
 [3690, 'WODONGA'],
 [3722, 'MANSFIELD'],
 [3232, 'SURF COAST'],
 [3156, 'KNOX'],
 [3156, 'YARRA RANGES'],
 [3156, 'CASEY'],
 [3713, 'MURRINDINDI'],
 [3713, 'MANSFIELD'],
 [3377, 'ARARAT RURAL'],
 [3377, 'NORTHERN GRAMPIANS'],
 [3377, 'PYRENEES'],
 [3816, 'BAW BAW'],
 [3816, 'CARDINIA'],
 [3960, 'SOUTH GIPPSLAND'],
 [3269, 'CORANGAMITE'],
 [3763, 'MURRINDINDI'],
 [3840, 'LATROBE'],
 [3699, 'ALPINE'],
 [3699, 'UNINCORPORATED'],
 [3723, 'BENALLA RURAL'],
 [3723, 'WANGARATTA RURAL'],
 [3723, 'MANSFIELD'],
 [3723, 'YARRA RANGES'],
 [3723, 'UNINCORPORATED'],
 [3113, 'NILLUMBIK'],
 [3113, 'MANNINGHAM'],
 [3174, 'GREATER DANDENONG'],
 [3490, 'MILDURA RURAL'],
 [3944, 'MORNINGTON'],
 [3292, 'GLENELG'],
 [3585, 'SWAN HILL RURAL'],
 [3585, 'GANNAWARRA'],
 [3660, 'MURRINDINDI'],
 [3660, 'MITCHELL'],
 [3175, 'GREATER DANDENONG'],
 [3228, 'SURF COAST'],
 [3182, 'PORT PHILLIP'],
 [3460, 'HEPBURN'],
 [3238, 'COLAC OTWAY'],
 [3396, 'YARRIAMBIACK'],
 [3140, 'YARRA RANGES'],
 [3683, 'INDIGO'],
 [3892, 'EAST GIPPSLAND']]

In [36]:
len(track_lga)

86

## Change postcodes to LGA and separated by comma

In [37]:
track_selected['LGA'] = ''

In [38]:
for idx,row in track_selected.iterrows():
    track_selected = track_selected.copy()
    lga_string = ''
    for lists in track_lga:
        
        # look for postcodes that are in track_lga lists
        if row['POST_CODE'] == lists[0]:
            lga_string += lists[1] + ',' # replace postcodes with LGA and separate by comma
    
    track_selected.at[idx,'LGA'] = lga_string # change 'LGA' column to LGAs

In [39]:
track_selected

,PARK_NAME,POST_CODE,CATEGORY,LGA
0,Australian Alps Walking Track,3825,Tracks/Trails,"BAW BAW,LATROBE,"
1,Ballarat-Skipton Railtrail,3350,Tracks/Trails,"BALLARAT,"
2,Barmah Lakes Loop Track,3639,Tracks/Trails,"MOIRA,"
3,Bayside Trail - Williamstown-Brighton,3000,Tracks/Trails,"MELBOURNE,"
4,Beehive Falls Trail,3381,Tracks/Trails,"NORTHERN GRAMPIANS,ARARAT RURAL,"
...,...,...,...,...
110,Wilsons Prom Circuit Trail,3960,Tracks/Trails,"SOUTH GIPPSLAND,"
111,Wirrawilla Walk - Toolangi State Forest,3777,Tracks/Trails,"YARRA RANGES,MURRINDINDI,"
112,Wonderland Loop Walk,3381,Tracks/Trails,"NORTHERN GRAMPIANS,ARARAT RURAL,"
113,Woolshed Falls Historic Walk,3747,Tracks/Trails,"INDIGO,WANGARATTA RURAL,"
114,Wreck Beach Trail,3238,Tracks/Trails,"COLAC OTWAY,"

In [40]:
import re
pattern = re.compile(r'\W\B') # patterns like ',' or ';' and etc.

In [41]:
# remove the comma at the end of string (e.g 'BAW BAW,LATROBE,')
for idx, row in track_selected.iterrows():
    track_selected = track_selected.copy()
    track_selected.at[idx, 'LGA'] = re.sub(pattern, '', row['LGA'])

In [42]:
track_selected

,PARK_NAME,POST_CODE,CATEGORY,LGA
0,Australian Alps Walking Track,3825,Tracks/Trails,"BAW BAW,LATROBE"
1,Ballarat-Skipton Railtrail,3350,Tracks/Trails,BALLARAT
2,Barmah Lakes Loop Track,3639,Tracks/Trails,MOIRA
3,Bayside Trail - Williamstown-Brighton,3000,Tracks/Trails,MELBOURNE
4,Beehive Falls Trail,3381,Tracks/Trails,"NORTHERN GRAMPIANS,ARARAT RURAL"
...,...,...,...,...
110,Wilsons Prom Circuit Trail,3960,Tracks/Trails,SOUTH GIPPSLAND
111,Wirrawilla Walk - Toolangi State Forest,3777,Tracks/Trails,"YARRA RANGES,MURRINDINDI"
112,Wonderland Loop Walk,3381,Tracks/Trails,"NORTHERN GRAMPIANS,ARARAT RURAL"
113,Woolshed Falls Historic Walk,3747,Tracks/Trails,"INDIGO,WANGARATTA RURAL"
114,Wreck Beach Trail,3238,Tracks/Trails,COLAC OTWAY

In [43]:
# create a list to store idx and LGA pair
track_lga_list = []

for idx, row in track_selected.iterrows():
    if not row['LGA'].isalpha():
        LGA_list = row['LGA'].split(',')
        temp = []
        temp.append(idx)
        temp.append(LGA_list)
        
        track_lga_list.append(temp)

In [44]:
track_lga_list

[[0, ['BAW BAW', 'LATROBE']],
 [4, ['NORTHERN GRAMPIANS', 'ARARAT RURAL']],
 [5, ['PYRENEES', 'ARARAT RURAL']],
 [6, ['GOLDEN PLAINS', 'GREATER GEELONG']],
 [7, ['GREATER BENDIGO']],
 [9, ['YARRA RANGES', 'MURRINDINDI']],
 [12, ['MILDURA RURAL']],
 [14, ['MILDURA RURAL']],
 [16, ['EAST GIPPSLAND']],
 [17, ['COLAC OTWAY']],
 [18, ['BASS COAST']],
 [19, ['MELBOURNE', 'PORT PHILLIP']],
 [20, ['MOYNE', 'WARRNAMBOOL']],
 [21, ['SOUTHERN GRAMPIANS']],
 [23, ['EAST GIPPSLAND']],
 [24, ['HINDMARSH', 'YARRIAMBIACK']],
 [25, ['EAST GIPPSLAND']],
 [26, ['EAST GIPPSLAND']],
 [27, ['MOUNT ALEXANDER']],
 [29, ['WELLINGTON', 'LATROBE']],
 [30, ['GOLDEN PLAINS', 'GREATER GEELONG']],
 [31, ['MACEDON RANGES']],
 [32, ['EAST GIPPSLAND']],
 [33, ['']],
 [34, ['EAST GIPPSLAND']],
 [35, ['ALPINE', 'UNINCORPORATED']],
 [36, ['INDIGO', 'WANGARATTA RURAL']],
 [38, ['MOUNT ALEXANDER']],
 [39, ['SOUTH GIPPSLAND', 'BAW BAW']],
 [40, ['MACEDON RANGES']],
 [44, ['SURF COAST']],
 [45, ['MILDURA RURAL']],
 [46, ['KNOX', 'YARRA RANGES', 'CASEY']],
 [47, ['MURRINDINDI', 'MANSFIELD']],
 [50, ['ARARAT RURAL', 'NORTHERN GRAMPIANS', 'PYRENEES']],
 [51, ['BAW BAW', 'CARDINIA']],
 [52, ['SOUTH GIPPSLAND']],
 [54, ['NORTHERN GRAMPIANS', 'ARARAT RURAL']],
 [55, ['COLAC OTWAY']],
 [56, ['MOYNE', 'WARRNAMBOOL']],
 [58, ['COLAC OTWAY']],
 [63, ['SOUTH GIPPSLAND']],
 [65, ['BAW BAW', 'LATROBE']],
 [66, ['NORTHERN GRAMPIANS', 'ARARAT RURAL']],
 [67, ['ALPINE', 'UNINCORPORATED']],
 [68,
  ['BENALLA RURAL',
   'WANGARATTA RURAL',
   'MANSFIELD',
   'YARRA RANGES',
   'UNINCORPORATED']],
 [69, ['ALPINE', 'UNINCORPORATED']],
 [70, ['ALPINE', 'UNINCORPORATED']],
 [71, ['NILLUMBIK', 'MANNINGHAM']],
 [72, ['NORTHERN GRAMPIANS', 'ARARAT RURAL']],
 [73, ['NORTHERN GRAMPIANS', 'ARARAT RURAL']],
 [74, ['NORTHERN GRAMPIANS', 'ARARAT RURAL']],
 [75, ['']],
 [76, ['GREATER DANDENONG']],
 [77, ['GREATER BENDIGO']],
 [78, ['MILDURA RURAL']],
 [82, ['SOUTH GIPPSLAND']],
 [83, ['EAST GIPPSLAND']],
 [84, ['NORTHERN GRAMPIANS', 'ARARAT RURAL']],
 [85, ['SWAN HILL RURAL', 'GANNAWARRA']],
 [87, ['MURRINDINDI', 'MITCHELL']],
 [88, ['SURF COAST']],
 [89, ['GREATER DANDENONG']],
 [91, ['SURF COAST']],
 [93, ['YARRA RANGES', 'MURRINDINDI']],
 [94, ['PORT PHILLIP']],
 [97, ['ALPINE', 'UNINCORPORATED']],
 [98, ['EAST GIPPSLAND']],
 [99, ['SOUTH GIPPSLAND']],
 [101, ['SOUTH GIPPSLAND']],
 [102, ['COLAC OTWAY']],
 [104, ['MOYNE', 'WARRNAMBOOL']],
 [105, ['ALPINE', 'UNINCORPORATED']],
 [106, ['BAW BAW', 'LATROBE']],
 [107, ['YARRA RANGES']],
 [109, ['EAST GIPPSLAND']],
 [110, ['SOUTH GIPPSLAND']],
 [111, ['YARRA RANGES', 'MURRINDINDI']],
 [112, ['NORTHERN GRAMPIANS', 'ARARAT RURAL']],
 [113, ['INDIGO', 'WANGARATTA RURAL']],
 [114, ['COLAC OTWAY']]]

In [45]:
# false_pairs are something like [25, ['Port Phillip']] where the second element in the list returns False when tested with
# str.isalpha() but actually it is a one-element-list. The reason that caused this is that this element has a white space in
# its string
false_pairs = []
for pairs in track_lga_list:
    if len(pairs[1]) == 1:
        false_pairs.append(pairs)

In [46]:
for pairs in false_pairs:
    
    track_lga_list.remove(pairs)

In [47]:
track_lga_list

[[0, ['BAW BAW', 'LATROBE']],
 [4, ['NORTHERN GRAMPIANS', 'ARARAT RURAL']],
 [5, ['PYRENEES', 'ARARAT RURAL']],
 [6, ['GOLDEN PLAINS', 'GREATER GEELONG']],
 [9, ['YARRA RANGES', 'MURRINDINDI']],
 [19, ['MELBOURNE', 'PORT PHILLIP']],
 [20, ['MOYNE', 'WARRNAMBOOL']],
 [24, ['HINDMARSH', 'YARRIAMBIACK']],
 [29, ['WELLINGTON', 'LATROBE']],
 [30, ['GOLDEN PLAINS', 'GREATER GEELONG']],
 [35, ['ALPINE', 'UNINCORPORATED']],
 [36, ['INDIGO', 'WANGARATTA RURAL']],
 [39, ['SOUTH GIPPSLAND', 'BAW BAW']],
 [46, ['KNOX', 'YARRA RANGES', 'CASEY']],
 [47, ['MURRINDINDI', 'MANSFIELD']],
 [50, ['ARARAT RURAL', 'NORTHERN GRAMPIANS', 'PYRENEES']],
 [51, ['BAW BAW', 'CARDINIA']],
 [54, ['NORTHERN GRAMPIANS', 'ARARAT RURAL']],
 [56, ['MOYNE', 'WARRNAMBOOL']],
 [65, ['BAW BAW', 'LATROBE']],
 [66, ['NORTHERN GRAMPIANS', 'ARARAT RURAL']],
 [67, ['ALPINE', 'UNINCORPORATED']],
 [68,
  ['BENALLA RURAL',
   'WANGARATTA RURAL',
   'MANSFIELD',
   'YARRA RANGES',
   'UNINCORPORATED']],
 [69, ['ALPINE', 'UNINCORPORATED']],
 [70, ['ALPINE', 'UNINCORPORATED']],
 [71, ['NILLUMBIK', 'MANNINGHAM']],
 [72, ['NORTHERN GRAMPIANS', 'ARARAT RURAL']],
 [73, ['NORTHERN GRAMPIANS', 'ARARAT RURAL']],
 [74, ['NORTHERN GRAMPIANS', 'ARARAT RURAL']],
 [84, ['NORTHERN GRAMPIANS', 'ARARAT RURAL']],
 [85, ['SWAN HILL RURAL', 'GANNAWARRA']],
 [87, ['MURRINDINDI', 'MITCHELL']],
 [93, ['YARRA RANGES', 'MURRINDINDI']],
 [97, ['ALPINE', 'UNINCORPORATED']],
 [104, ['MOYNE', 'WARRNAMBOOL']],
 [105, ['ALPINE', 'UNINCORPORATED']],
 [106, ['BAW BAW', 'LATROBE']],
 [111, ['YARRA RANGES', 'MURRINDINDI']],
 [112, ['NORTHERN GRAMPIANS', 'ARARAT RURAL']],
 [113, ['INDIGO', 'WANGARATTA RURAL']]]

### create a new dataframe to store all the multiple LGA and corresponding records

In [48]:
track_duplicate_LGA = pd.DataFrame(columns=['LGA', 'PARK_NAME', 'CATEGORY'])

In [49]:

track_lga_final_list = []
track_park_name_list = []
track_category_list = []

# store data in corresponding columns
for lists in track_lga_list:
    for lga in lists[1]:
        track_lga_final_list.append(lga)
        track_park_name = track_selected.iloc[lists[0]]['PARK_NAME']
        track_category = track_selected.iloc[lists[0]]['CATEGORY']
        
        track_park_name_list.append(track_park_name)
        track_category_list.append(track_category)

In [50]:
track_duplicate_LGA['LGA'] = track_lga_final_list
track_duplicate_LGA['PARK_NAME'] = track_park_name_list
track_duplicate_LGA['CATEGORY'] = track_category_list

In [51]:
track_duplicate_LGA

                   LGA                                PARK_NAME       CATEGORY
0              BAW BAW            Australian Alps Walking Track  Tracks/Trails
1              LATROBE            Australian Alps Walking Track  Tracks/Trails
2   NORTHERN GRAMPIANS                      Beehive Falls Trail  Tracks/Trails
3         ARARAT RURAL                      Beehive Falls Trail  Tracks/Trails
4             PYRENEES                            Beeripmo Walk  Tracks/Trails
..                 ...                                      ...            ...
80         MURRINDINDI  Wirrawilla Walk - Toolangi State Forest  Tracks/Trails
81  NORTHERN GRAMPIANS                     Wonderland Loop Walk  Tracks/Trails
82        ARARAT RURAL                     Wonderland Loop Walk  Tracks/Trails
83              INDIGO             Woolshed Falls Historic Walk  Tracks/Trails
84    WANGARATTA RURAL             Woolshed Falls Historic Walk  Tracks/Trails

[85 rows x 3 columns]

### Remove multiple LGA rows from original dataframe in order to concatenate the duplicate LGA dataframe and the single LGA rows dataframe

In [52]:
for pairs in track_lga_list:
    track_selected.drop(pairs[0],inplace=True)

In [53]:
track_selected.drop(columns=['POST_CODE'], inplace=True)

In [54]:
track_selected

                                 PARK_NAME       CATEGORY              LGA
1               Ballarat-Skipton Railtrail  Tracks/Trails         BALLARAT
2                  Barmah Lakes Loop Track  Tracks/Trails            MOIRA
3    Bayside Trail - Williamstown-Brighton  Tracks/Trails        MELBOURNE
7                   Bendigo Bushland Trail  Tracks/Trails  GREATER BENDIGO
8                    Benwerrin Nature Walk  Tracks/Trails          GLENELG
..                                     ...            ...              ...
107          Warburton Rail Trail Lilydale  Tracks/Trails     YARRA RANGES
108                White Box Walking Trail  Tracks/Trails           INDIGO
109                  Wilderness Coast Walk  Tracks/Trails   EAST GIPPSLAND
110             Wilsons Prom Circuit Trail  Tracks/Trails  SOUTH GIPPSLAND
114                      Wreck Beach Trail  Tracks/Trails      COLAC OTWAY

[75 rows x 3 columns]

In [55]:
track_final_df = pd.concat([track_selected, track_duplicate_LGA])

In [56]:
track_final_df

                                  PARK_NAME       CATEGORY                 LGA
1                Ballarat-Skipton Railtrail  Tracks/Trails            BALLARAT
2                   Barmah Lakes Loop Track  Tracks/Trails               MOIRA
3     Bayside Trail - Williamstown-Brighton  Tracks/Trails           MELBOURNE
7                    Bendigo Bushland Trail  Tracks/Trails     GREATER BENDIGO
8                     Benwerrin Nature Walk  Tracks/Trails             GLENELG
..                                      ...            ...                 ...
80  Wirrawilla Walk - Toolangi State Forest  Tracks/Trails         MURRINDINDI
81                     Wonderland Loop Walk  Tracks/Trails  NORTHERN GRAMPIANS
82                     Wonderland Loop Walk  Tracks/Trails        ARARAT RURAL
83             Woolshed Falls Historic Walk  Tracks/Trails              INDIGO
84             Woolshed Falls Historic Walk  Tracks/Trails    WANGARATTA RURAL

[160 rows x 3 columns]

## There are a few empty string entries in LGA column.
## To drop these rows, use np.nan to replace the empty strings then df.dropna()

In [57]:
import numpy as np
track_final_df['LGA'].replace('', np.nan, inplace=True)
track_final_df.dropna(subset=['LGA'],inplace=True)

In [58]:
track_park_swim = pd.concat([park_swim_df, track_final_df])

In [59]:
track_park_swim

,LGA,PARK_NAME,CATEGORY
1,BOROONDARA,Kate Campbell Reserve,Parks and gardens
6,BOROONDARA,Jack Otoole Reserve,Sportsfields and organised recreation
12,BOROONDARA,Hays Paddock,Parks and gardens
15,WYNDHAM,Bay Trail,Recreational Reserve
48,BOROONDARA,Boroondara Park,Parks and gardens
...,...,...,...
80,MURRINDINDI,Wirrawilla Walk - Toolangi State Forest,Tracks/Trails
81,NORTHERN GRAMPIANS,Wonderland Loop Walk,Tracks/Trails
82,ARARAT RURAL,Wonderland Loop Walk,Tracks/Trails
83,INDIGO,Woolshed Falls Historic Walk,Tracks/Trails
84,WANGARATTA RURAL,Woolshed Falls Historic Walk,Tracks/Trails

In [60]:
track_park_swim.drop_duplicates(keep='first',inplace=True)

In [61]:
track_park_swim

,LGA,PARK_NAME,CATEGORY
1,BOROONDARA,Kate Campbell Reserve,Parks and gardens
6,BOROONDARA,Jack Otoole Reserve,Sportsfields and organised recreation
12,BOROONDARA,Hays Paddock,Parks and gardens
15,WYNDHAM,Bay Trail,Recreational Reserve
48,BOROONDARA,Boroondara Park,Parks and gardens
...,...,...,...
80,MURRINDINDI,Wirrawilla Walk - Toolangi State Forest,Tracks/Trails
81,NORTHERN GRAMPIANS,Wonderland Loop Walk,Tracks/Trails
82,ARARAT RURAL,Wonderland Loop Walk,Tracks/Trails
83,INDIGO,Woolshed Falls Historic Walk,Tracks/Trails
84,WANGARATTA RURAL,Woolshed Falls Historic Walk,Tracks/Trails

In [62]:
track_park_swim.dropna(how='any',inplace=True)

## Some PARK_NAME contain partial address, separated by comma. E.X. 'Dandenong Creek Reserve 3, End of Bungalook Road'

## There are multiple ways to wrangle it but I'll separate the string by comma. I do this because this is the safest pattern to do. Writing RE could be problem because it's hard to capture comma when the patterns following comma is hard to predict

## For example r'\W\B[\W\w]+' will capture the comma in the first string example but it won't capture this one: W (Jacko) Jackson Reserve, 29-31 Rendcomb

In [63]:
# create a list to store idx and park_name pair
park_name_list = []

for idx, row in track_park_swim.iterrows():
    if ',' in row['PARK_NAME']:
        park_list = row['PARK_NAME'].split(',')
        temp = []
        temp.append(idx)
        temp.append(park_list)
        
        park_name_list.append(temp)

In [64]:
park_name_list

[[82, ['Drains', ' Hawthorn']],
 [136, ['Trunk Sewer', ' South Eastern']],
 [175, ['Retarding Basins', ' Hawthorn East']],
 [179, ['Burke Road Billabong Reserve', ' Kew East']],
 [595, ['Drains', ' Ashburton (Camberwell)']],
 [818, ['350a Tooronga Rd', ' Hawthorn']],
 [1081, ['Parkland Rds', ' Doncaster East']],
 [1101, ['Flood Plains', ' Improvement - Taylors Creek']],
 [1119, ['Reserve', ' Manningham', ' Drainage']],
 [1188, ['Flood Plains', ' Improvement - Ruffeys Creek']],
 [1232, ['Parkland Rds', ' Doncaster East']],
 [1382, ['Parkland Rds', ' Doncaster East']],
 [1440, ['Retarding Basins', ' Wetherby Road (Doncaster)']],
 [1456, ['Flood Plains', ' Yarra River']],
 [1534, ['Retarding Basins', ' Andersons Creek']],
 [1543, ['Drains', ' Porter Street']],
 [1836, ['Parkland Rds', ' Doncaster East']],
 [3170, ['Melbourne Water retarding basin', ' Montrose']],
 [5009, ['Kurrajong Reserve', ' 1 Kurrajong Avenue']],
 [5014, ['Mullum Creek Reserve 4', ' 18 Reserve Road']],
 [5018, ['Tania Reserve', ' Rear 26 Tania Court']],
 [5019,
  ['Mullum Creek Reserve 3', ' Oban to Sonia Street', ' rear of properties']],
 [5024, ['Jeffrey Reserve 1', ' 50A Jeffrey Drive']],
 [5025, ['Jeffrey Reserve 3', ' Rear 62-70 Jeffrey Drive']],
 [5027, ['Mullum Creek Reserve 1', ' End of Maggs Street']],
 [5045, ['Appletree Hill Reserve', ' Handasyde Avenue']],
 [5050, ['Dandenong Creek Reserve 6', ' 191 Heatherdale Road']],
 [5058, ['Wyreena Reserve', ' 13-23 Hull Road']],
 [5060, ['Leeds Reserve', ' 15-19 Leeds Drive']],
 [5061, ['Hochkins Ridge Flora Reserve', ' 24 Nangathan Way']],
 [5063, ['Hochkins Ridge Flora Reserve', ' 24 Nangathan Way']],
 [5080, ['Glenvale Reserve', ' 50-58 Glenvale Road']],
 [5081, ['Walhalla Reserve', ' 14A Walhalla Drive']],
 [5082, ['Loughnan Reserve ', ' 121-123 Loughnan Road']],
 [5085, ['Staley Gardens', ' Seymour Street']],
 [5087, ['A.F.B. Long Reserve', ' 78A Dublin Rd']],
 [5098, ['Cobain Reserve', ' 6-7 Cobain Court']],
 [5102, ['Bedford Reserve 2', ' 7-9 Bedford Road']],
 [5111, ['Brentwood Park', ' 122-130 Lincoln Road']],
 [5115, ['Heathmont Reserve 1', ' 15A Great Ryrie Street']],
 [5118, ['Ainslie Park', ' Hinkley Avenue']],
 [5139, ['Herman Pump Reserve', ' 30A Tagell Road']],
 [5150, ['Wombalano Park', ' 33A Canterbury']],
 [5159, ['Retarding Basins', ' Upper Bungalook Creek - Maroondah']],
 [5164, ['Maidstone Reserve', ' 47 Maidstone St']],
 [5172, ['Highland Reserve 1', ' Rear 3-21Highland Avenue']],
 [5175, ['Dresden Reserve 1', ' 15-23 Dresden Avenue']],
 [5185, ['Apex Park', ' 19A Reumah Court']],
 [5191, ['Adina Reserve', ' 5 Adina Close']],
 [5197, ['Woodlands Reserve', ' 34A Woodlands Road']],
 [5220, ['Westmore Reserve', ' 285A Canterbury Road']],
 [5228, ['Longview Reserve', ' 20-22 Shane Crescent']],
 [5231, ['Canterbury Reserve', ' Canterbury Road']],
 [5240, ['Hume Reserve', ' 27-39 Hume Street']],
 [5244, ['Cuthbert Reserve', ' 20A Cuthbert']],
 [5256, ['Clarke Reserve', ' 15-17 Clarke Drive']],
 [5258, ['H.E. Parker Reserve', ' 154 Heathmont Road']],
 [5263, ['Ringwood Civic Reserve', ' Braeside Avenue']],
 [5264, ['Gracedale Reserve', ' 28-30 Hume Street']],
 [5266, ['Viviani Reserve', ' 31-37 Viviani Crescent']],
 [5267, ['Taralla Creek Reserve 5', ' 117-119 Bayswater']],
 [5268, ['Waterloo Reserve', ' 25A Waterloo Street']],
 [5269, ['Federation Estate', ' 30A Greenwood Avenue']],
 [5276, ['Carol Hancock Reserve', ' 14 Carol Hancock Place']],
 [5281, ['Drains', ' Croydon']],
 [5293, ['Knee Reserve', ' 16A Barnard Crescent']],
 [5297, ['Dandenong Creek Reserve 1', ' Rear 38-44 Barrow Drive']],
 [5298, ['New Reserve', ' West 58 Nelson Street']],
 [5301, ['Bungalook Conservation Reserve', ' 16 Clarkedale Rise']],
 [5303, ['Bungalook Conservation Reserve', ' 16 Clarkedale Rise']],
 [5304, ['Civic Reserve', ' 1 Civic Square']],
 [5306, ['Ringwood Lake Reserve', ' Maroondah Hwy']],
 [5312, ['Oban Woods Reserve', ' 28A Barnsdale Way']],
 [5326, ['Mundara Reserve', ' 46-50 Mundara Drive']],
 [5339, ['Shibor Reserve', ' 23-25 Shibor Drive']],
 [5340, ['Heatherbrae Reserve', ' 21 Grant Crescent']],
 [5347, ["O'Neill Reserve", " Rear of 7 O'Neill Way"]],
 [5354, ['Connolly Reserve', ' End of Connolly Crescent']],
 [5356, ['Illuminate Reserve', ' 20 Maygrand Close']],
 [5358, ['Silcock Reserve', ' William Road']],
 [5367, ['Glen Park', ' 30-48 Glen Park']],
 [5369, ['Peter Vergers Reserve', ' 537 Maroondah Hwy']],
 [5370, ['Dandenong Creek Reserve 5', ' Between Dorset & Colchester Roads']],
 [5375, ['Wonga Retarding Basin', ' Cnr Wonga Road and Mundara Drive']],
 [5378, ['Kalinda Modified Urban Forest Bushland', ' Ringwood']],
 [5380, ['Dandenong Creek Reserve 3', ' End of Bungalook Road']],
 [5388, ['Gilda Reserve', ' 1A Gilda Court']],
 [5393, ['Independance Reserve', ' 12 Sandy Wynd']],
 [5398, ['Nursery Reserve', ' 37A Nursery Road']],
 [5399, ['San Remo Reserve', ' Cnr San Remo Rd & Cameron Rd']],
 [5401, ['Appletree Hill Reserve', ' Handasyde Avenue']],
 [5412, ['Proclamation Park', ' 11-13 Sylvia Grove']],
 [5413, ['Norwood Reserve ', ' 125A Warrandyte Road']],
 [5414, ['Stringybark Flora Reserve', ' 116A Exeter Road']],
 [5418, ['Linda Reserve', ' 2A Linda Drive']],
 [5421, ['Greenwood Park ', ' 5A Greenwood Avenue']],
 [5422, ['Federico Retarding Basin Reserve', ' 158-160 Wonga Road']],
 [5424, ['Clyde Reserve', ' 35 Manifold Court']],
 [5433, ['Lavender Reserve', ' 32A Great Ryrie Street']],
 [5441, ['Maygrand Reserve', ' 6 Maygrand Close']],
 [5448, ['Janson Reserve', ' Janson Court']],
 [5460, ['Cielterre Reserve 1', ' 7-9 Cielterre Avenue']],
 [5469, ['Cantala Reserve', ' 9 Werac Drive']],
 [5472, ['Bronhill Reserve', ' 53 Bronhill Road']],
 [5477, ['Civic Reserve', ' 1 Civic Square']],
 [5480, ['Wantirna Rd', ' Ringwood']],
 [5485, ['Taralla Creek Reserve 2', ' 61-69 Norton Road']],
 [5489, ['Andrew Reserve', ' 17A Andrew Street and 6 Munro Street']],
 [5490, ['Smithdene Reserve', ' 7A Smithdene Avenue']],
 [5508, ['Dorset Recreation Reserve', ' 367 Dorset Road']],
 [5514, ['Reynolds Ave', ' Ringwood']],
 [5515, ['Georges Reserve', ' 35 Georges Road']],
 [5519, ['Bypass Reserve 2', ' Between Ringwood and Warrandyte road']],
 [5526, ['Dandenong Creek Reserve 1', ' Rear 38-44 Barrow Drive']],
 [5541, ['Mullum Creek Reserve 6', ' Suda Avenue']],
 [5544, ['Gladys Reserve', ' 23-29 Gladys Grove']],
 [5553, ['Taralla Creek Reserve 1', ' 342 Dorset Road']],
 [5560, ['Manifold Reserve 3', ' 21 Manifold Court']],
 [5561, ['Miller Reserve', ' 29 Miller Road']],
 [5566, ['Taralla Creek Reserve 6', ' Teak Avenue']],
 [5570, ['Panorama Reserve', ' 28A Panorama Ave']],
 [5580, ['Grandfil Reserve', ' Kenmare Avenue']],
 [5587, ['Pandora Reserve', ' 8 Pandora Crescent']],
 [5595, ['Sellick Reserve 1', ' 55-73 Sellick Drive']],
 [5600, ['Towerhill Reserve', ' 21A Towerhill Drive']],
 [5616, ['Charles Allen Reserve', ' 119-131 Hull Rd']],
 [5619, ['Drains', ' Upper Bungalook Creek']],
 [5620, ['Gracedale Park', ' 38-48 Gracedale Avenue']],
 [5630, ['Danielle Reserve', ' 17A Danielle Crescent']],
 [5643, ['Drains', ' Upper Dandenong Creek D.S.']],
 [5668, ['Kelvin Reserve', ' 14 Cormistom Road']],
 [5685, ['Herman Pump Reserve', ' 30A Tagell Road']],
 [5704, ['Tamar Reserve', ' 14-16 Tamar']],
 [5710, ['Kiloran Reserve', ' 25-33 Kiloran Avenue']],
 [5718, ['Freeman Reserve', ' 24-26 Freeman Street']],
 [5724, ['Cheong Park', ' 84-100 Bayswater Road']],
 [5726, ['Retarding Basins', ' Andersons Creek']],
 [5728, ['Alto Reserve', ' 78-86 Alto Avenue']],
 [5732, ['Forest Reserve', ' 8 Forest Court']],
 [5760, ['Eunice Reserve', ' 6-10 Eunice Crt']],
 [5764, ['Felix Reserve', ' 100-102 Felix Crescent']],
 [5770, ['Vasey Reserve', ' 16 Cecil Circuit']],
 [5771, ['Everard Reserve 1', ' 17D Everard Road']],
 [5772, ['The Pass Reserve', ' 43 Eastfield Road']],
 [5773, ['Tanbridge Reserve', ' 36 Tanbridge Way']],
 [5776, ['Mersey Reserve 1', ' 1A Mersey Street']],
 [5783, ['Pinetree Reserve', ' 13 Pinetree Close']],
 [5784, ['Minkara Reserve', ' 13 Minkara Crt']],
 [5787, ['Galtymore Reserve', ' 6A Galtymore Close']],
 [5792, ['Eden Valley Reserve 1', ' 2A Eden Valley Road']],
 [5795, ['Landstrom Reserve', ' 18-20 Landstrom Quadrant']],
 [5798, ['Paddlewheeler Reserve', ' 8 Paddlewheeler Pocket']],
 [5802, ['Hexham Reserve 2', ' 14A Hexham Street']],
 [5805, ['Waterview Reserve', ' 39A Waterview Court']],
 [5810, ['Strathfield Reserve', ' 8-18 Strathfield Parade']],
 [5817, ['Retarding Basins', ' North Ringwood']],
 [5818, ['Mount View Reserve', ' 2 Churchill Road']],
 [5825, ['Boronia Reserve', ' 12 Boronia Av']],
 [5827, ['Kyamba Reserve', ' 11 Kyamba Court']],
 [5835, ['Bennison Reserve', ' Bennison Street']],
 [5842, ['Bayswater Reserve 1', ' 314 Bayswater Road']],
 [5846, ['Lena Reserve', ' Between Lena Grove and Campbell Street']],
 [5848, ['Wyett Reserve', ' 12 Wyett Crt']],
 [5853, ['Ringwood Lake Reserve', ' Maroondah Hwy']],
 [5862, ['Jennings Reserve', ' 12-14 Jennnings Rd']],
 [5877, ['Ormond Reserve 2', ' 12A Ormond Place']],
 [5880, ['Lipscombe Park', ' 2A Sandgate Avenue']],
 [5886, ['Marraroo Reserve', ' 11 Custer Grove']],
 [5897, ['Chamberlain Reserve', ' 15 Chamberlain Drive']],
 [5907, ['Warrien Reserve', ' 18-52 Warrien Road']],
 [5911, ['Chandra Reserve 1', ' 9 Oliver Court']],
 [5913, ['Gairns Reserve', ' 1 Gairns Court']],
 [5914, ['Greenhill Reserve', ' 54 Greenhill Road']],
 [5931, ['Ringwood Public Golf Course', ' Canterbury Road Ringwood']],
 [5933, ['Grayswood Reserve', ' 23-25 Watermoor Avenue']],
 [5934, ['Heathmont Reserve', ' 264 Canterbury Road']],
 [5936, ['Wonga Reserve', ' 159 Wonga Road']],
 [5939, ['Highland Reserve 2', ' 13A Highland Boulevard']],
 [5940, ['Laura Reserve', ' 30 Toolimerin Avenue']],
 [5943, ['Belmont Park', ' 97-101 Belmont Road']],
 [5944, ['Dandenong Creek Reserve 5', ' Between Dorset & Colchester Roads']],
 [5946, ['Toolimerin Reserve', ' 42 Toolimerin Avenue']],
 [5958, ['Woody Reserve', ' 6A Woody Link']],
 [5959, ['The Gateway Reserve', ' Between The Gateway & School Walk']],
 [5960, ['Woodland Park', ' 44A Azarow Circuit']],
 [5963, ['Holland Reserve', ' 39A Holland']],
 [5964, ['Croydon Park', ' 213-215 Mt Dandenong Road']],
 [5966, ['Jeffrey Reserve 2', ' 74A Jeffrey Drive']],
 [5968, ['Oban Reserve ', ' Cnr. Frederic & Oban']],
 [5970, ['W (Jacko) Jackson Reserve', ' 29-31 Rendcomb']],
 [5971, ['Burdekin Avenue Reserve 2', ' 79A Burdekin Avenue']],
 [5974, ['Morris Reserve', ' 1 Morris Road']],
 [5978, ['Bedford Park', ' Bedford Road']],
 [5979, ['Mullum Reserve', ' 58-60 Mullum road']],
 [5981, ['Peter Vergers Reserve', ' 537 Maroondah Hwy']],
 [5989, ['Lester Reserve', ' 7-17 Lester Av']],
 [6229, ['Retarding Basins', ' Riddell Road']],
 [6255, ['Retarding Basins', ' Police Road']],
 [6392, ['Reserve 1 Market Drive', ' Bayswater North']],
 [6599, ['Reserve 4 Market Drive', ' Bayswater North']],
 [6642, ['Wantirna Rd', ' Ringwood']],
 [7162, ['Drains', ' Ferny Creek']],
 [7299, ['Retarding Basins', ' Sasses Avenue']],
 [7347, ['Middleborough Rd', ' Box Hill North']],
 [7355, ['10-12 Sprinvale Rd', ' Nunawading']],
 [7364, ['Retarding Basins', ' Wetherby Road (Doncaster)']],
 [7419, ['Koolunga Native Reserve (CL part)', ' Ferntree Gully']],
 [8004, ['31 The Quadrangle', ' Glen Waverley']],
 [8020, ['34 Craig Hill Drive', ' Wheelers Hill']],
 [8034, ['15 Akuna Avenue', ' Notting Hill']],
 [8036, ['7-11 Janice Road', ' Glen Waverley']],
 [8049, ['7 Tom Begg Court', ' Wheelers Hill']],
 [8057, ['586-612 Huntingdale Road', ' Mount Waverley']],
 [8064, ['17A Sherwood Road', ' Mount Waverley']],
 [8073, ['14A Sherwood Road', ' Mount Waverley']],
 [8084, ['24 Bramley Crescent', ' Wheelers Hill']],
 [8089, ['30A Sherwood Road', ' Mount Waverley']],
 [8092, ['850-880 Highbury Road', ' Glen Waverley']],
 [8113, ['50-60 Holmbury Boulevard', ' Mulgrave']],
 [8115, ['62-64 Holmbury Boulevard', ' Mulgrave']],
 [8118, ['575-595 Police Road', ' Mulgrave']],
 [8125, ['53 Shaftsbury Drive', ' Mulgrave']],
 [8128, ['14 Shaftsbury Drive', ' Mulgrave']],
 [8147, ['43-51 Fraser Street', ' Glen Waverley']],
 [8192, ['1m1 Monash Freeway', ' Chadstone']],
 [8193, ['4A May Court', ' Glen Waverley']],
 [8194, ['1A Tulloch Grove', ' Glen Waverley']],
 [8195, ['6A Golden View Court', ' Wheelers Hill']],
 [8242, ['2A Faulkiner Street', ' Clayton']],
 [8303, ['Drains', ' Burwood South Drainage Scheme Stage 1']],
 [8326, ['8 Miners Court', ' Mulgrave']],
 [8458, ['22 Sunnybrook Drive', ' Wheelers Hill']],
 [8512, ['450 Highbury Road', ' Mount Waverley']],
 [8520, ['3 Duval Court', ' Wheelers Hill']],
 [8642, ['49-51 Mayfield Drive', ' Mount Waverley']],
 [8660, ['49-55 Wave Avenue', ' Mount Waverley']],
 [8707, ['5 Rathdowne Way', ' Mulgrave']],
 [8738, ['1 Padey Drive', ' Mulgrave']],
 [8753, ['15 Keylana Boulevard', ' Mount Waverley']],
 [8780, ['20 Lords Avenue', ' Mulgrave']],
 [8797, ['6 Liverpool Street', ' Mulgrave']],
 [8801, ['8 Brockhoff Drive', ' Burwood']],
 [8809, ['10 Lords Avenue', ' Mulgrave']],
 [8817, ['4 Lansdowne Circuit', ' Mulgrave']],
 [8824, ['23 Notre Dame Parade', ' Mulgrave']],
 [8831, ['4 Notre Dame Parade', ' Mulgrave']],
 [8842, ['203 Brandon Park Drive', ' Wheelers Hill']],
 [8843, ['23 Lords Avenue', ' Mulgrave']],
 [8847, ['12 Rodway Court', ' Burwood']],
 [8850, ['11A Heytesbury Place', ' Mulgrave']],
 [8855, ['22 Brockhoff Drive', ' Burwood']],
 [8900, ['9 Burbidge Close', ' Burwood']],
 [8914, ['31 Jacana Street', ' Chadstone']],
 [8917, ['19A Samada Street', ' Notting Hill']],
 [8921, ['14-16 Atkinson Street', ' Chadstone']],
 [8939, ['14 Jacana Court', ' Chadstone']],
 [8968, ['9 Strand Close', ' Glen Waverley']],
 [8969, ['46A Grenfell Road', ' Mount Waverley']],
 [8971, ['17 St Georges Court', ' Glen Waverley']],
 [9013, ['586-612 Huntingdale Road', ' Mount Waverley']],
 [9138, ['Retarding Basins', ' Police Road']],
 [9149, ['1m1 Monash Freeway', ' Chadstone']],
 [9280, ['1-3 St Clair Crescent', ' Mount Waverley']],
 [9282, ['43-5 Sunnybrook Drive', ' Wheelers Hill']],
 [9309, ['923-925 High Street Road', ' Glen Waverley']],
 [9316, ['Retarding Basins', ' Waverly Road']],
 [9350, ['579-581 Waverley Road', ' Glen Waverley']],
 [9366, ['3A Sneddon Court', ' Mulgrave']],
 [9387, ['14 Gertrude Street', ' Mulgrave']],
 [9395, ['2a Lea Road', ' Mulgrave']],
 [9431, ['17A Patrick Street', ' Oakleigh East']],
 [9451, ['14-18 Torroodun Street', ' Mount Waverley']],
 [9482, ['Retarding Basins', ' Huntingdale Road']],
 [9489, ['Large Main', ' Mt View to Dandenong Main']],
 [9521, ['23A Fiander Avenue', ' Glen Waverley']],
 [9557, ['465-499 Police Road', ' Mulgrave']],
 [9581, ['2-6 Legana Street', ' Mount Waverley']],
 [9585, ['Rear 6 Devon Court', ' Mount Waverley']],
 [9652, ['264-268 Clayton Road', ' Clayton']],
 [9660, ['40 Grantham Terrace', ' Mulgrave']],
 [9663, ['27A Holmbury Boulevard', ' Mulgrave']],
 [9691, ['12 Trentbridge', ' Mulgrave']],
 [9692, ['Flood Plains', ' Improvement - Rose Creek']],
 [9695, ['22 Trentbridge Road', ' Mulgrave']],
 [9699, ['Flood Plains', ' Scotchmans Creek']],
 [9724, ['148-158 Jacksons Road', ' Mulgrave']],
 [9728, ['2A Lea Road', ' Mulgrave']],
 [9776, ['24 Baradine Street', ' Chadstone']],
 [9790, ['107 Coleman Parade', ' Glen Waverley']],
 [9881, ['624A Waverley Road', ' Glen Waverley']],
 [9939, ['2a Kelly Street', ' Chadstone']],
 [9958, ['25 highland Avenue', ' Oakleigh East']],
 [9983, ['Forster Rd', ' Mt Waverley']],
 [9988, ['701 Wellington Road', ' Wheelers Hill']],
 [10659, ['Bond', ' A.W. Reserve']],
 [10660, ['City West Water Reserve', ' The Parkway', ' Caroline']],
 [10662, ['Ginifer', ' J.J. Reserve']],
 [10668, ['Frazer', ' R. Reserve']],
 [10673, ['Hearn', ' V.L. Reserve']],
 [10676, ['Ford', ' A.H. Reserve']],
 [10691, ['Retarding Basins', ' Waverly Road']],
 [10767, ['Gray', ' J.T. Reserve']],
 [10857, ['Richards', ' R.K. Reserve']],
 [10868, ['Grieve', ' D. Reserve']],
 [10876, ['Ransom', ' G.H. Reserve']],
 [10880, ['Irwin', ' W.J. Reserve']],
 [10884, ['Langshaws', ' A.W. Reserve']],
 [10892, ['Stirling', ' G.F. Reserve']],
 [10898, ['Emery', ' F.A. Reserve']],
 [10915, ['Hosken', ' G.J. Reserve']],
 [10935, ['Cooper', ' R.J. Reserve']],
 [10940, ['McIntosh', ' S.G. Reserve']],
 [10982, ['O`Brien', ' J.F. Reserve']],
 [10983, ['Grant', ' J.K. Reserve']],
 [10984, ['Lee', ' H.W. Reserve']],
 [10989, ['Stewart', ' J.J. Reserve']],
 [10990, ['Carlsson', ' C.W. Reserve']],
 [10994, ['Knight Reserve', ' A.W. (Altona Meadows)']],
 [10997, ['Hubble', ' W.E. Reserve']],
 [10999, ['Rush', ' F. Reserve']],
 [11108, ['Drains', ' Kayes']],
 [11255, ['Kim', ' H.C. Reserve']],
 [11257, ['Cresser', ' W.G. Reserve']],
 [11331, ['Crofts', ' W.L.J. Reserve']],
 [11336, ['Clement', ' S.J. Reserve']],
 [11592, ['Kororoit Creek Flood Plains', ' Cherry Lake']],
 [11844, ['Taylors Rd.', ' Reserve No 1/Carbine Way']],
 [12075, ['Retarding Basins', ' Boundary Rd']],
 [12219, ['Flood Plains', ' Improvement - Steele Creek']],
 [12710, ['Large Water Supply Main', ' Off Green Gully', ' Kealba']],
 [12812, ['Steele St', ' Keilor Park']],
 [12952, ['Taylors Creek Frontage', ' Watergardens']],
 [13098, ['South Base Stone Historic Reserve', ' Werribee']],
 [13102, ['North Base Stone Historic Reserve', ' Tarneit']],
 [13145, ['Retarding Basin', ' Hume']],
 [13371, ['Drains', ' Kayes']],
 [13424, ['Drains', ' Forsyth Rd']],
 [13477, ['Flood Plains', ' Cherry Creek']],
 [14150, ['Woodlands Park', ' Essendon']],
 [14374, ['Flood Plains', ' Skeleton Creek']],
 [14418, ['Flood Plains', ' Improvement - Rose Creek']],
 [14520, ['Drains', ' Hutchison Rd']],
 [14896, ['adjacent to Treatment Plants', ' Brooklyn']],
 [15019, ['Aqueduct', ' Maroondah']],
 [15022, ['Flood Plains', ' Improvement - Salt Creek']],
 [15077, ['Drains', ' Yando Street']],
 [15092, ['Flood Plains', ' Plenty River']],
 [15258, ['Retarding Basins', ' Briar Hill']],
 [15470, ['Flood Plains', ' Improvement - Salt Creek surplus']],
 [15784, ['Large Main', ' Buckley Street']],
 [16035, ['VicTrack', ' Darebin']],
 [16119, ['Large Main', ' Preston - Reservoir to Merri Creek']],
 [16160, ['Flood Plains', ' improvement - Edgars Creek - Darebin']],
 [16203,
  ['Large Main', ' Melbourne Water', ' Preston - Nth Essendon Main No.1']],
 [16218, ['Drains', ' Merrilands (Preston)']],
 [17050, ['Galada Tamboore', ' Merri Creek']],
 [17079, ['Flood Plains', ' improvement - Edgars Creek']],
 [17567, ['Reserve', ' Whittlesea', ' Drainage']],
 [17870, ['Flood Plains', ' Improvement - Central Creek']],
 [17883, ['Glenn Cr', ' Reservoir']],
 [18161, ['Drains', ' Upper Hendersons Creek Drainage Scheme Stage 15']],
 [18348, ['Drains', ' The Lakes Boulevard']],
 [18845, ['Barry Rd Grasslands', ' Merri Creek- MWC land']],
 [19261, ['Drains', ' Aitken Creek']],
 [19430, ['Flood Plains', ' Merlynston Creek - Hume']],
 [19436, ['Large Main', ' Kenny St To Broadmeadows Reservoir']],
 [19875, ['Retarding Basins', ' Commonwealth Serum Laboratories']],
 [20443, ['Coburg North Linear Reserve (Drains', ' Merlynston)']],
 [20715, ['Galada Tamboore', ' Merri Creek']],
 [20739, ['Wheeler St Reserve', ' Pascoe Vale South']],
 [20807, ['Hume Hwy', ' Craigieburn']],
 [21362,
  ['Edgars Creek Parkland (Large Main',
   ' Melbourne Water',
   ' Preston - Nth Essendon Main No.1)']],
 [21374, ['Retarding Basin', ' Commonwealth Serum Laboratories']],
 [22042, ['Childrens Playground', ' St Andrews']],
 [22419, ['Flood Plains', ' Diamond Creek']],
 [22443, ['Flood Plains', ' Cherry Tree Creek']],
 [22447, ['Flood Plains', ' Plenty River']],
 [22482, ['Waterway', ' Dry Creek']],
 [22534, ['Main Rd', ' Diamond Creek']],
 [22939, ['Reservoirs', ' Plenty']],
 [23024, ['Retarding Basins', ' Hallam Valley']],
 [23028, ['Flood Plains', ' Improvement - Eumemmerring Creek']],
 [23033, ['Drainage // Reserve', ' Greater Dandenong']],
 [23039, ['Drains', ' Carrum Outfall']],
 [23106, ['Reservoirs', ' Dandenong']],
 [23206, ['Reservoirs', ' Dandenong']],
 [23367, ['Drains', ' Lyndhurst Drainage Scheme']],

In [65]:
track_park_swim

,LGA,PARK_NAME,CATEGORY
1,BOROONDARA,Kate Campbell Reserve,Parks and gardens
6,BOROONDARA,Jack Otoole Reserve,Sportsfields and organised recreation
12,BOROONDARA,Hays Paddock,Parks and gardens
15,WYNDHAM,Bay Trail,Recreational Reserve
48,BOROONDARA,Boroondara Park,Parks and gardens
...,...,...,...
80,MURRINDINDI,Wirrawilla Walk - Toolangi State Forest,Tracks/Trails
81,NORTHERN GRAMPIANS,Wonderland Loop Walk,Tracks/Trails
82,ARARAT RURAL,Wonderland Loop Walk,Tracks/Trails
83,INDIGO,Woolshed Falls Historic Walk,Tracks/Trails
84,WANGARATTA RURAL,Woolshed Falls Historic Walk,Tracks/Trails

In [66]:
for lists in park_name_list:
    track_park_swim.at[lists[0],'PARK_NAME'] = lists[1][0]

In [67]:
track_park_swim

,LGA,PARK_NAME,CATEGORY
1,BOROONDARA,Kate Campbell Reserve,Parks and gardens
6,BOROONDARA,Jack Otoole Reserve,Sportsfields and organised recreation
12,BOROONDARA,Hays Paddock,Parks and gardens
15,WYNDHAM,Bay Trail,Recreational Reserve
48,BOROONDARA,Boroondara Park,Parks and gardens
...,...,...,...
80,MURRINDINDI,Wirrawilla Walk - Toolangi State Forest,Tracks/Trails
81,NORTHERN GRAMPIANS,Wonderland Loop Walk,Tracks/Trails
82,ARARAT RURAL,Drains,Tracks/Trails
83,INDIGO,Woolshed Falls Historic Walk,Tracks/Trails
84,WANGARATTA RURAL,Woolshed Falls Historic Walk,Tracks/Trails

## There are some PARK_NAME of NO DATA

In [68]:
track_park_swim.loc[track_park_swim['PARK_NAME'] == 'NO DATA']

                     LGA PARK_NAME                               CATEGORY
6013                KNOX   NO DATA          Natural attraction (reserves)
6021                KNOX   NO DATA                      Parks and gardens
6024                KNOX   NO DATA                   Recreational Reserve
6256                KNOX   NO DATA  Sportsfields and organised recreation
7521          WHITEHORSE   NO DATA                      Parks and gardens
7821          WHITEHORSE   NO DATA                   Recreational Reserve
8070          WHITEHORSE   NO DATA          Natural attraction (reserves)
12157            WYNDHAM   NO DATA                      Parks and gardens
12164            WYNDHAM   NO DATA                   Recreational Reserve
13099            WYNDHAM   NO DATA          Natural attraction (reserves)
13221            WYNDHAM   NO DATA  Sportsfields and organised recreation
15088            BANYULE   NO DATA                      Parks and gardens
15579            BANYULE   NO DATA          Natural attraction (reserves)
15967            BANYULE   NO DATA                   Recreational Reserve
20081           MORELAND   NO DATA          Natural attraction (reserves)
20095           MORELAND   NO DATA                      Parks and gardens
23061  GREATER DANDENONG   NO DATA                      Parks and gardens
23093  GREATER DANDENONG   NO DATA  Sportsfields and organised recreation
23108  GREATER DANDENONG   NO DATA                   Recreational Reserve
23125  GREATER DANDENONG   NO DATA          Natural attraction (reserves)
24388          GLEN EIRA   NO DATA  Sportsfields and organised recreation
33501           KINGSTON   NO DATA                      Parks and gardens
34100          MELBOURNE   NO DATA                      Parks and gardens
34119          MELBOURNE   NO DATA          Natural attraction (reserves)
36017          FRANKSTON   NO DATA          Natural attraction (reserves)
37103          FRANKSTON   NO DATA                      Parks and gardens
38174         MANNINGHAM   NO DATA          Natural attraction (reserves)

In [69]:
track_park_swim.drop(track_park_swim[track_park_swim['PARK_NAME'] == 'NO DATA'].index, inplace=True)

## There are some entries with len(PARK_NAME) = 1, which are some places that aren't parks. So I'll remove these.

## When you do len(df['column name']) you are just getting one number, namely the number of rows in the DataFrame (i.e., the length of the column itself). If you want to apply len to each element in the column, use df['column name'].map(len)

In [71]:
track_park_swim['PARK_NAME'].replace('', np.nan, inplace=True)
track_park_swim.dropna(subset=['PARK_NAME'],inplace=True)

In [70]:
track_park_swim['LGA'].replace('', np.nan, inplace=True)
track_park_swim.dropna(subset=['LGA'],inplace=True)

In [72]:
track_park_swim

,LGA,PARK_NAME,CATEGORY
1,BOROONDARA,Kate Campbell Reserve,Parks and gardens
6,BOROONDARA,Jack Otoole Reserve,Sportsfields and organised recreation
12,BOROONDARA,Hays Paddock,Parks and gardens
15,WYNDHAM,Bay Trail,Recreational Reserve
48,BOROONDARA,Boroondara Park,Parks and gardens
...,...,...,...
80,MURRINDINDI,Wirrawilla Walk - Toolangi State Forest,Tracks/Trails
81,NORTHERN GRAMPIANS,Wonderland Loop Walk,Tracks/Trails
82,ARARAT RURAL,Drains,Tracks/Trails
83,INDIGO,Woolshed Falls Historic Walk,Tracks/Trails
84,WANGARATTA RURAL,Woolshed Falls Historic Walk,Tracks/Trails

In [76]:
track_park_swim.drop(track_park_swim[track_park_swim['PARK_NAME'].str.split().map(len) < 2].index)

,LGA,PARK_NAME,CATEGORY
1,BOROONDARA,Kate Campbell Reserve,Parks and gardens
6,BOROONDARA,Jack Otoole Reserve,Sportsfields and organised recreation
12,BOROONDARA,Hays Paddock,Parks and gardens
15,WYNDHAM,Bay Trail,Recreational Reserve
48,BOROONDARA,Boroondara Park,Parks and gardens
...,...,...,...
79,YARRA RANGES,Wirrawilla Walk - Toolangi State Forest,Tracks/Trails
80,MURRINDINDI,Wirrawilla Walk - Toolangi State Forest,Tracks/Trails
81,NORTHERN GRAMPIANS,Wonderland Loop Walk,Tracks/Trails
83,INDIGO,Woolshed Falls Historic Walk,Tracks/Trails
84,WANGARATTA RURAL,Woolshed Falls Historic Walk,Tracks/Trails

In [77]:
track_park_swim.drop(track_park_swim[track_park_swim['PARK_NAME'].str.split().map(len) < 2].index, inplace=True)

## There are some entries that named 'Trunk Sewer' under PARK_NAME. This is likely a wrong entry. Hence we remove these records

In [80]:
track_park_swim.drop(track_park_swim[track_park_swim['PARK_NAME'] == 'Trunk Sewer'].index, inplace=True)

In [82]:
# generate LGA_ID
LGA_ID = []
counter = 800000
for i in range(len(track_park_swim)):
    counter += 1
    LGA_ID.append(counter)

In [83]:
# create final dataframe
final_df = pd.DataFrame({'LGA_ID' : LGA_ID,
                       'LGA' : track_park_swim['LGA'],
                       'PARK_NAME' : track_park_swim['PARK_NAME'],
                       'CATEGORY' : track_park_swim['CATEGORY']})

In [84]:
final_df

,LGA_ID,LGA,PARK_NAME,CATEGORY
1,800001,BOROONDARA,Kate Campbell Reserve,Parks and gardens
6,800002,BOROONDARA,Jack Otoole Reserve,Sportsfields and organised recreation
12,800003,BOROONDARA,Hays Paddock,Parks and gardens
15,800004,WYNDHAM,Bay Trail,Recreational Reserve
48,800005,BOROONDARA,Boroondara Park,Parks and gardens
...,...,...,...,...
79,810185,YARRA RANGES,Wirrawilla Walk - Toolangi State Forest,Tracks/Trails
80,810186,MURRINDINDI,Wirrawilla Walk - Toolangi State Forest,Tracks/Trails
81,810187,NORTHERN GRAMPIANS,Wonderland Loop Walk,Tracks/Trails
83,810188,INDIGO,Woolshed Falls Historic Walk,Tracks/Trails
84,810189,WANGARATTA RURAL,Woolshed Falls Historic Walk,Tracks/Trails

In [85]:
final_df.to_csv('LGA with park and swim and track.csv', index=False)

In [89]:
final_df.iloc[8341]

LGA_ID                                                  808342
LGA                                                   KINGSTON
PARK_NAME    Old Wells Road Tree Reserve - West Section 1 P...
CATEGORY                                  Recreational Reserve
Name: 33192, dtype: object